const express = require("express");
const app = express();
const cors = require("cors");
const userRouter = require("./routers/userRouter");
const organizationRouter = require("./routers/organizationRouter");
const productRouter = require("./routers/productRouter.js");
const customerRouter = require("./routers/customerRouter.js");
const supplierRouter = require("./routers/supplierRouter.js");
const purchaseOrderRouter = require("./routers/purchaseOrderRouter.js");
const inventoryRouter = require("./routers/inventoryRouter.js");
const stockRouter = require("./routers/stockRouter.js");
const accountRouter = require("./routers/accountRouter.js");
const jornalRouter = require("./routers/jornalRouter.js");
const jornalEntryRouter = require("./routers/jornalEntryRouter.js");
const categoryRouter = require("./routers/categoryRouter.js");
const stockTransferRouter = require("./routers/stockTransferRouter.js");
const loanRouter = require("./routers/loanRouter.js");
const installmentRouter = require("./routers/installmentRouter.js");
const authRouter = require("./authRouters/authRouter");
const globalErrorHandling = require("./utils/globalErrorHandling");
const AppError = require("./utils/appError");
const cookieParser = require("cookie-parser");
app.use(express.json());
app.use(cors());
app.use(cookieParser());
app.use("/api/v1/users", userRouter);
app.use("/api/v1/auth", authRouter);
app.use("/api/v1/organizations", organizationRouter);
app.use("/api/v1/products", productRouter);
app.use("/api/v1/customers", customerRouter);
app.use("/api/v1/suppliers", supplierRouter);
app.use("/api/v1/purchaseOrders", purchaseOrderRouter);
app.use("/api/v1/inventories", inventoryRouter);
app.use("/api/v1/stocks", stockRouter);
app.use("/api/v1/accounts", accountRouter);
app.use("/api/v1/jornals", jornalRouter);
app.use("/api/v1/jornalEntry", jornalEntryRouter);
app.use("/api/v1/category", categoryRouter);
app.use("/api/v1/stockTransfer", stockTransferRouter);
app.use("/api/v1/loans", loanRouter);
app.use("/api/v1/installments", installmentRouter);
app.use("/", (req, res, next) => {
  res.send("Welcome to ERP");
});
app.all("*", (req, res, next) => {
  next(new AppError(`can't find ${req.originalUrl} on this server`, 404));
});
app.use(globalErrorHandling);
module.exports = app;
